trigger:
  - main  # ou la branche que vous utilisez

pool:
  vmImage: 'ubuntu-latest'

variables:
  app_build_command: 'npm run docs:build'  # Remplacez par votre commande de build réelle

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'  # Choisissez la version de Node.js appropriée
    displayName: 'Installer Node.js'

  - script: |
      npm install
    displayName: 'Installer les dépendances'

  - script: |
      echo "Exécution de la commande de build : $(app_build_command)"
      $(app_build_command)
    displayName: 'Exécuter la commande de build'

  - script: |
      echo "Déploiement de l’application..."
      # Ajoutez ici vos commandes de déploiement si nécessaire
    displayName: 'Déploiement'
